### ISSUE TITLE
High cpu utilization on file upload

### ISSUE THREAD

**Issue by p1ratrulezzz** [alexbers/mtprotoproxy#1]
Hello. I've tested this server software and it works great though if I send some file (Only one client was connected) the server CPU gets 100% load. I believe it is because of encryption, but I'm not python expert.

**Comment by alexbers** [comment]
Hello, thanks for using the software. 

This happens because I am using python AES implementation, which is really slow. I plan to move to faster C implementation soon. I'll write to you when its done.

**Comment by alexbers** [comment]
The problem should be fixed by https://github.com/alexbers/mtprotoproxy/commit/b42ddffef2a584c21e77214d1653728bbc7289e0 and https://github.com/alexbers/mtprotoproxy/commit/9153ee2c903c32175851b02b700b334664198a38. Now the program tries to use fast pycrypto first and then fallbacks to slow pyaes. With pycrypto, the encryption and decryption are 665.67 times faster.

Could you please check if everything is good.

**Comment by p1ratrulezzz** [comment]
Hi. Thanks for a quick fix, now load is ~10% using one client, norm koroche)

Additionaly I had to install crypto module

```bash
sudo apt install python3-crypto
```
