### ISSUE TITLE
implications of not using a TLS 1.3 host

### ISSUE THREAD

**Issue by FreedomPrevails** [alexbers/mtprotoproxy#130]
I have added a custom TLS_DOMAIN to config.py and I am getting a warning "The MASK_HOST www.xxxx.com is not TLS 1.3 host, this is not recommended"
Why is it important that the TLS version has to be 1.3 ? TLS 1.3 is quite new and is not supported on cpanel using apache yet.
What are the implications of not using a TLS 1.3 host ?

**Comment by seriyps** [comment]
The thing is that when proxy can't decode client's request as valid telegram fake-TLS connection, it just proxies client's request to MASK_HOST and returns whatever this host answers in response.
Now let's say DPI sees a lots of traffic toproxy host, sees that all of it is TLS1.3 and it tries to send just normal TLS1.3 request to this host with domain name from SNI. Itr then will look very suspicious if proxy host answers "tls1.3 is not supported, only 1.1 and 1.2 are supported" because that's what MASK_HOST says

**Comment by FreedomPrevails** [comment]
So mtprotoproxy simulates TLS 1.3 traffic and thats why TLS_DOMAIN should use TLS 1.3 as well ?

**Comment by seriyps** [comment]
Yes, mtproto fake-tls looks like TLS1.3 and only 1.3. TLS_DOMAIN not "should use" TLSv1.3, but it should support TLSv1.3 if you don't want to look bit suspicious.

**Comment by erfantkerfan** [comment]
@alexbers 
answered
close please

**Comment by FreedomPrevails** [comment]
@erfantkerfan Are you github's open issues police ? lol
`Just kidding`

**Comment by erfantkerfan** [comment]
I'm dedicated to law and order!
👮
(J.K. too)
