### ISSUE TITLE
Proxy spawns 60-120 connections

### ISSUE THREAD

**Issue by black-cerberon** [alexbers/mtprotoproxy#169]
Why proxy spawns too much connections in background without any activity? Only 2 users stay connected in idle.

**Comment by alexbers** [comment]
The proxy connects to the parent proxy before the client connect to the proxy because it is faster for the client to connect and gives a better ping.

If this is a problem, you can change MAX_CONNS_IN_POOL constant in the code to 1. But 120 connections shouldn't be a problem even on the cheapest servers.

**Comment by black-cerberon** [comment]
Thanks. I set it to 4 instead 64 and not feel some difference in speed.
