### ISSUE TITLE
Not Opening photo And video

### ISSUE THREAD

**Issue by rahyar25** [alexbers/mtprotoproxy#2]
I tested this software on the server
posting of photos and content is goods
But there's a problem opening photos and videos  .
This seems to be due to the limited Telegram IP in the TG_DATACENTERS section.
please check this problem.
thanks .

**Comment by alexbers** [comment]
Hello,

By some reason the telegram client was sending negative datacenter index trying to open the photos. May be, this is a protocol feature, the protocol specification isn't published yet.

This problem should be fixed by https://github.com/alexbers/mtprotoproxy/commit/b42ddffef2a584c21e77214d1653728bbc7289e0

Please, recheck with the latest version.

**Comment by rahyar25** [comment]
The problem was resolved
thanks
