### ISSUE TITLE
Connection Failed!

### ISSUE THREAD

**Issue by Yakuzaa7** [alexbers/mtprotoproxy#266]
Hello friends.
I setup Mtproxy and everything is fine, but after a while the access to the server is cut off (either via ssh and Mtproto) but the server is not filtered and the problem is solved after Hard Reboot.
(This proxy is used personally)
My Location : Iran
Server specification :
Datacenter : Hetzner-SATA (Germany)
OS : Linux ubuntu21.04 64Bit
Ram : 2GB
CPU : 1 Core

**Comment by erfantkerfan** [comment]
All proxies are beeing blocked some how

**Comment by Yakuzaa7** [comment]
> All proxies are beeing blocked some how

Ok, but this proxy is not filtered
This proxy is sometimes interrupted but works fine

**Comment by erfantkerfan** [comment]
Mine too
Even ssh is okay

**Comment by ghasrfakhri** [comment]
It seems that the filtering devices detect mtproto packets and just block them.

**Comment by andrey-makhnutin** [comment]
I started noticing today that the Telegram client fails to connect via the proxy most of the time, but situation gets better immediately after proxy restart and sometimes connection comes through without a restart, but after a lot of failed attempts.

Did a little debugging and found out that connection between client and a proxy is being closed by the proxy after an exception is thrown here https://github.com/alexbers/mtprotoproxy/blob/446682521b9a5cc0eb7297fc05a61758db2df8b0/mtprotoproxy.py#L1584
in a task `tg_connect_reader_to_writer`, while piping data from client to Telegram servers. The exception thrown is `ConnectionResetError('Connection lost',)`.

I have a suspicion that it has to do with connection pooling. Since my proxy server is not a high volume one, maybe pooled prepared connections to TG servers become stale, causing proxy to terminate the connection to a client.

I fixed this problem on my server by setting `TgConnectionPool.MAX_CONNS_IN_POOL` to zero, disabling pooling altogether. And now I don't have a ton of idling connections to TG servers, and the proxy seems to work much more stably.

**Comment by MAHDITX** [comment]
> 

how should I set `TgConnectionPool.MAX_CONNS_IN_POOL` to zero ?

**Comment by MAHDITX** [comment]
> I fixed this problem on my server by setting `TgConnectionPool.MAX_CONNS_IN_POOL` to zero, disabling pooling altogether. And now I don't have a ton of idling connections to TG servers, and the proxy seems to work much more stably.

how should I set `TgConnectionPool.MAX_CONNS_IN_POOL` to zero ?

**Comment by Yakuzaa7** [comment]
> I started noticing today that the Telegram client fails to connect via the proxy most of the time, but situation gets better immediately after proxy restart and sometimes connection comes through without a restart, but after a lot of failed attempts.
> 
> Did a little debugging and found out that connection between client and a proxy is being closed by the proxy after an exception is thrown here
> 
> https://github.com/alexbers/mtprotoproxy/blob/446682521b9a5cc0eb7297fc05a61758db2df8b0/mtprotoproxy.py#L1584
> 
> 
> in a task `tg_connect_reader_to_writer`, while piping data from client to Telegram servers. The exception thrown is `ConnectionResetError('Connection lost',)`.
> I have a suspicion that it has to do with connection pooling. Since my proxy server is not a high volume one, maybe pooled prepared connections to TG servers become stale, causing proxy to terminate the connection to a client.
> 
> I fixed this problem on my server by setting `TgConnectionPool.MAX_CONNS_IN_POOL` to zero, disabling pooling altogether. And now I don't have a ton of idling connections to TG servers, and the proxy seems to work much more stably.

Thank you for your answer.  But I did not understand exactly, I do not know how to do it.  Note also that my problem is not only the proxy in case of failure, but also my access to SSH will be lost and to solve the problem I have to Hard Reboot the server.  Or worse, I have to reinstall the operating system.  Always after changing the operating system, the connection to the proxy may work for several days without any problems.
