### ISSUE TITLE
My Server Filtered!!!

### ISSUE THREAD

**Issue by 0x9a** [alexbers/mtprotoproxy#64]
hi in 24 hours my ip filtered how can stop it??

**Comment by alexbers** [comment]
hi, please try to add SECURE_ONLY=True to the config.py, this will make the proxy harder to detect

**Comment by 0x9a** [comment]
> 
> 
> hi, please try to add SECURE_ONLY=True to the config.py, this will make the proxy harder to detect

when i use it and use tag dont show my channel!!

**Comment by HirbodBehnam** [comment]
Hi if you are in Iran, you can do this:
1. Buy a VPS that is located in Iran and another in a foreign country.
2. Install Mtproto proxy on the one located in a foreign country.
3. Enable "SECURE_ONLY". This option is available only in master branch. This option will drop the connections that do not use random padding. (Ones without `dd` in the beginning)
4. On the Iranian VPS, route all traffic on a specific port to the port that your proxy is running on your foreign server.
Let's guess that your proxy on foreign server is running on port 8888. Then you have to choose a port on your Persian server and route all traffic on that port to port 8888, and you main server.
[Here](https://www.debuntu.org/how-to-redirecting-network-traffic-to-a-new-ip-using-iptables/) is how you can do this with iptables.
5. Replace IP and your port in your proxy link. (With your the persian server)
This is because Iran cannot filter local servers.

**Comment by 0x9a** [comment]
> 
> 
> hi, please try to add SECURE_ONLY=True to the config.py, this will make the proxy harder to detect

i enabled but blocked!

**Comment by alexbers** [comment]
Could you please provide more information which can help understand why it may be blocked.
- is it running in Iran or outside?
- how many users were connected before the blocking?
- how the proxy was advertised?

**Comment by alexbers** [comment]
also it is important which hosting are you using? On a few of them they are founding proxy very fast

**Comment by 0x9a** [comment]
out side server 

original MTProxy 17k
this script 4k user

proxy cahnnels

**Comment by mostafa-v** [comment]
> Hi if you are in Iran, you can do this:
> 
>     1. Buy a VPS that is located in Iran and another in a foreign country.
> 
>     2. Install Mtproto proxy on the one located in a foreign country.
> 
>     3. Enable "SECURE_ONLY". This option is available only in master branch. This option will drop the connections that do not use random padding. (Ones without `dd` in the beginning)
> 
>     4. On the Iranian VPS, route all traffic on a specific port to the port that your proxy is running on your foreign server.
>        Let's guess that your proxy on foreign server is running on port 8888. Then you have to choose a port on your Persian server and route all traffic on that port to port 8888, and you main server.
>        [Here](https://www.debuntu.org/how-to-redirecting-network-traffic-to-a-new-ip-using-iptables/) is how you can do this with iptables.
> 
>     5. Replace IP and your port in your proxy link. (With your the persian server)
> 
>     6. Share the link.
> 
> 
> This is because Iran cannot filter local servers.

Hi

Anyone tested this solution???
Which IP will be shown in Telegram active sessions? Iran VPS IP or client IP?

**Comment by HirbodBehnam** [comment]
Hi @mostafa-v 
I haven't tested it my self but about 5 other people tested that and reported that it is working fine. Also I'm not sure about active sessions maybe the foreign VPS; because the Iran VPS is acting just like a router.
Also another good idea is to do not share proxy links. Instead, put secret, IP and port in different messages and tell the subscribers (to channel) to set that up manually by entering it in their settings. This is because Iran has some kinda bots that search channels for proxy links and filter them. If you put them in different messages, there is a high probability that hey won't detect it.
