### ISSUE TITLE
encrypt traffics!!

### ISSUE THREAD

**Issue by 0x9a** [alexbers/mtprotoproxy#65]
hi 
master.
you can select option for encrypt traffics with P2P or PGP ?
this option can help we for unban proxys

**Comment by alexbers** [comment]
hi
all traffic is already encrypted several times. All telegram clients doesn't support p2p nor pgp, so they will be unable to connect

**Comment by 0x9a** [comment]
ISP's follow Traffics and block it!

**Comment by HirbodBehnam** [comment]
Hi
I don't think that is possible at all. Because MTProtoProxy is designed to encrypt data with this algorithm. If you chnage the encryption algorithm, you actually change the whole protocol. And nobody could connect.
Maybe (Totally not sure) you can write your own protocol and implement that in a custom client. I mean you have to create ANOTHER telegram client in order to implement your own protocol.

**Comment by seriyps** [comment]
@HirbodBehnam Yep, I can confirm both your statements.

**Comment by alexbers** [comment]
The new TLS protocol was implemented and added in both server and clients.
