### ISSUE TITLE
new version problem on windows server

### ISSUE THREAD

**Issue by ea1234567** [alexbers/mtprotoproxy#67]
proxy old version works perfectly on windows server
but when i lunch new version,clients cant connect to telegram
if u want i can give you access to my vps

tnx

**Comment by alexbers** [comment]
this is because I patched the old client for you to compensate time skew on your server. You can find the patch and reapply it on the new version.

But more easy way is to ask a server admin to adjust the clock.

In the future I plan to make a proxy to ask the time from the time-server and use it instead of local time.

**Comment by ea1234567** [comment]
but my server time zone is same as client time zone
old proxy is ok

which patch do you mean? i cant find it

**Comment by alexbers** [comment]
if you are using git, the "git diff" command should show the difference between the original version and the patched one
