### ISSUE TITLE
Fail2ban

### ISSUE THREAD

**Issue by black-cerberon** [alexbers/mtprotoproxy#71]
Hello. Can you add fail2ban-compatible output log, when auth was failed?

**Comment by alexbers** [comment]
Hello, to add this log you can write
print_err("Failed to auth", writer.get_extra_info('peername')[0])

just before this line:
while await reader.read(EMPTY_READ_BUF_SIZE):

Please feel free to change a message to any format you want. To write to stdout instead of stderr a print function can be used instead print_err

**Comment by black-cerberon** [comment]
Thank you. I hope it will be included in future.
