### ISSUE TITLE
Ping too high

### ISSUE THREAD

**Issue by hmt1376** [alexbers/mtprotoproxy#80]
I'm using a raspberry pi 3 B+ (latest version) and everything works fine. but the ping is way too high: usually between 800 to 1000 ms.

Any solutions?

**Comment by alexbers** [comment]
It shouldn't be so long. How the internet connection is organized? Do you use vpn or similar technology on the host?

**Comment by hmt1376** [comment]
The internet speed is fast and I haven't had any issues regarding latency with it. I don't use a VPN on the host. I also used google cloud platform and ran the proxy server on an Ubuntu VM and got the same ping range. I even modified TO_CLT_BUFSIZE = 163840 and TO_TG_BUFSIZE = 655360 as it was mentioned in #50 but the ping is still too high.

**Comment by alexbers** [comment]
The buffers size shouldn't affect the ping time. The ping can be big if the proxy is far away from telegram servers or if the client is far away from proxy. You can choose the location of the proxy to be as close to telegram servers as possible.

Also if you are measuring ping time using telegram client, the time it tell can be not precise, because it also counts the time of connection establishing. In real life the connection is established only one time in the beginning and persists till something go wrong.

**Comment by alexbers** [comment]
Could you please retry with the latest version, some changes were made to make the proxy ping faster
