### ISSUE TITLE
proxy runs but client can't connect

### ISSUE THREAD

**Issue by masoudelete** [alexbers/mtprotoproxy#89]
I run the program with no problem but I can't connect with telegram, I have a digitalocean ubuntu droplet in Germany, I'm not behind NAT and i installed NTP:
`apt-get install ntp`
and I tried setting my timezone to Germany and Iran (where i am), I tried connecting with telegram desktop, mobile different ISP's and vpn but nothing worked
and I am a newbie so consider that.
please help me
thanks in advance

**Comment by alexbers** [comment]
Here is a command sequence how to get the proxy running in the Digital Ocean:
```
apt update
apt install -y docker-compose
git clone -b stable https://github.com/alexbers/mtprotoproxy.git; cd mtprotoproxy
docker-compose up --build -d
docker-compose logs
# the proxy address will be printed
```

In the DO you don't have to install any time sync services because it is precise by default.

The reason why it doesn't work can be that the ip address of DO server can be already block in Iran. Also it may be a problem with command sequence.

You can try to recreate the droplet with the default OS and use the provided command sequence. Also you can try to create droplets in the other countries.

**Comment by masoudelete** [comment]
Thanks man, my problem got fixed. thanks for the fast reply. now i have another issue about uploading images in certain ISP's but i will create a new issue for.

this problem got fixed I'm closing this
